# Generated by Django 3.2.7 on 2021-09-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
